services:
  db:
    image: public.ecr.aws/docker/library/postgres:alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=dev
      - POSTGRES_USER=dev
      - POSTGRES_PASSWORD=dev
      - TZ=Europe/Bratislava
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./setup.sql:/docker-entrypoint-initdb.d/setup.sql:ro

  customer-service:
    image: simple-quarkus-app/customer-service:0.1.0
    restart: unless-stopped
    ports:
      - "8081:8080"
    environment:
      - QUARKUS_DATASOURCE_JDBC_URL=jdbc:postgresql://db:5432/dev?currentSchema=customer
    depends_on:
      - db
    labels:
      - traefik.enable=true
      - traefik.http.routers.customer-service.rule=PathPrefix(`/api/customers`)
      - traefik.http.routers.customer-service.entrypoints=web
      - traefik.http.services.customer-service.loadbalancer.server.port=8080

  reservation-service:
    image: simple-quarkus-app/reservation-service:0.1.0
    restart: unless-stopped
    ports:
      - "8082:8080"
    environment:
      - QUARKUS_DATASOURCE_JDBC_URL=jdbc:postgresql://db:5432/dev?currentSchema=reservation
    depends_on:
      - db
    labels:
      - traefik.enable=true
      - traefik.http.routers.reservation-service.rule=PathPrefix(`/api/reservations`)
      - traefik.http.routers.reservation-service.entrypoints=web
      - traefik.http.services.reservation-service.loadbalancer.server.port=8080

  room-service:
    image: simple-quarkus-app/room-service:0.1.0
    restart: unless-stopped
    ports:
      - "8084:8080"
    environment:
      - QUARKUS_DATASOURCE_JDBC_URL=jdbc:postgresql://db:5432/dev?currentSchema=room
    depends_on:
      - db
    labels:
      - traefik.enable=true
      - traefik.http.routers.room-service.rule=PathPrefix(`/api/rooms`)
      - traefik.http.routers.room-service.entrypoints=web
      - traefik.http.services.room-service.loadbalancer.server.port=8080

  room-reservation-service:
    image: simple-quarkus-app/room-reservation-service:0.1.0
    restart: unless-stopped
    ports:
      - "8083:8080"
    environment:
      - QUARKUS_REST_CLIENT__CustomerApiClient__URL=http://customer-service/api
      - QUARKUS_REST_CLIENT__ReservationApiClient__URL=http://reservation-service/api
      - QUARKUS_REST_CLIENT__RoomApiClient__URL=http://room-service/api
    depends_on:
      - customer-service
      - reservation-service
      - room-service
    labels:
      - traefik.enable=true
      - traefik.http.routers.room-reservation-service.rule=PathPrefix(`/api/room-reservations`)
      - traefik.http.routers.room-reservation-service.entrypoints=web
      - traefik.http.services.room-reservation-service.loadbalancer.server.port=8080

  traefik:
    image: traefik:v3.2
    command:
      - "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entryPoints.web.address=:80"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

volumes:
  db-data:
