### Create new
POST {{url}}/customers
Content-Type: application/json

{
  "firstName": "Jack",
  "lastName": "Daniels"
}

### Modify
PUT {{url}}/customers/2
Content-Type: application/json

{
  "firstName": "Jimbo",
  "lastName": "Rocket"
}

### Get all
GET {{url}}/customers

### Get single
GET {{url}}/customers/1

### Delete
DELETE {{url}}/customers/1
