quarkus:
  datasource:
    db-kind: postgresql
    jdbc:
      url: jdbc:postgresql://localhost:5432/dev?currentSchema=reservation
    username: dev
    password: dev

  liquibase:
    migrate-at-start: true

  log:
    category:
      "sk.janobono":
        level: DEBUG
    level: INFO

  http:
    root-path: /api

"%dev":
  quarkus:
    http:
      port: 8082
