openapi: 3.1.0
info:
  title: Customer Service API
  description: Customer Service API
  version: 0.1.0
paths:
  /customers:
    get:
      operationId: getCustomers
      tags:
        - Customers
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                type:
                  - array
                items:
                  $ref: "#/components/schemas/customer"
    post:
      operationId: addCustomer
      tags:
        - Customers
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/customerContent"
      responses:
        201:
          description: Customer successfully created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/customer"
  /customers/{id}:
    parameters:
      - name: id
        schema:
          type: integer
          format: int64
        in: path
        required: true
    put:
      operationId: setCustomer
      tags:
        - Customers
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/customerContent"
      responses:
        200:
          description: Customer successfully updated
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/customer"
    delete:
      operationId: deleteCustomer
      tags:
        - Customers
      responses:
        200:
          description: Customer successfully deleted
    get:
      operationId: getCustomer
      tags:
        - Customers
      responses:
        200:
          description: Customer successfully returned
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/customer"
components:
  schemas:
    customer:
      type: object
      properties:
        id:
          type: integer
          format: int64
        firstName:
          type: string
        lastName:
          type: string
    customerContent:
      type: object
      required:
        - firstName
        - lastName
      properties:
        firstName:
          type: string
          x-field-extra-annotation: "@jakarta.validation.constraints.NotBlank"
        lastName:
          type: string
          x-field-extra-annotation: "@jakarta.validation.constraints.NotBlank"

