openapi: 3.1.0
info:
  title: Reservation Service API
  description: Reservation Service API
  version: 0.1.0
paths:
  /reservations:
    get:
      parameters:
        - in: query
          name: date
          schema:
            type: string
            format: date
            example: "2024-10-31"
          required: false
      operationId: getReservations
      tags:
        - Reservations
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                type:
                  - array
                items:
                  $ref: "#/components/schemas/reservation"
    post:
      operationId: addReservation
      tags:
        - Reservations
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/reservationContent"
      responses:
        201:
          description: Reservation successfully created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/reservation"
  /reservations/{id}:
    parameters:
      - name: id
        schema:
          type: integer
          format: int64
        in: path
        required: true
    put:
      operationId: setReservation
      tags:
        - Reservations
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/reservationContent"
      responses:
        200:
          description: Reservation successfully updated
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/reservation"
    delete:
      operationId: deleteReservation
      tags:
        - Reservations
      responses:
        200:
          description: Reservation successfully deleted
    get:
      operationId: getReservation
      tags:
        - Reservations
      responses:
        200:
          description: Reservation successfully returned
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/reservation"
components:
  schemas:
    reservation:
      type: object
      properties:
        id:
          type: integer
          format: int64
        roomId:
          type: integer
          format: int64
        customerId:
          type: integer
          format: int64
        date:
          type: string
          format: date
          example: "2024-10-31"
    reservationContent:
      type: object
      required:
        - roomId
        - customerId
        - date
      properties:
        roomId:
          type: integer
          format: int64
        customerId:
          type: integer
          format: int64
        date:
          type: string
          format: date
          example: "2024-10-31"
