openapi: 3.1.0
info:
  title: Room Service API
  description: Room Service API
  version: 0.1.0
paths:
  /rooms:
    get:
      operationId: getRooms
      tags:
        - Rooms
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                type:
                  - array
                items:
                  $ref: "#/components/schemas/room"
    post:
      operationId: addRoom
      tags:
        - Rooms
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/roomContent"
      responses:
        201:
          description: Room successfully created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/room"
  /rooms/{id}:
    parameters:
      - name: id
        schema:
          type: integer
          format: int64
        in: path
        required: true
    put:
      operationId: setRoom
      tags:
        - Rooms
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/roomContent"
      responses:
        200:
          description: Room successfully updated
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/room"
    delete:
      operationId: deleteRoom
      tags:
        - Rooms
      responses:
        200:
          description: Room successfully deleted
    get:
      operationId: getRoom
      tags:
        - Rooms
      responses:
        200:
          description: Room successfully returned
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/room"
components:
  schemas:
    room:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        roomNumber:
          type: string
    roomContent:
      type: object
      required:
        - name
        - roomNumber
      properties:
        name:
          type: string
          x-field-extra-annotation: "@jakarta.validation.constraints.NotBlank"
        roomNumber:
          type: string
          x-field-extra-annotation: "@jakarta.validation.constraints.NotBlank"
